version: 2
jobs:
  build:
    docker: &docker
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: Run tests
          command: go test ./...

  deploy:
    docker: *docker
    steps:
      - checkout
      - deploy:
          name: Release
          command: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          # ref: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
